#!/bin/bash

BASEDIR="$(readlink -f $HOME/build/toolchain)"

case "$ARCH" in
amd64|x86_64|x64)
	export ARCH=x86_64
	export HOST=x86_64-linux-android
	TOOLCHAIN="$BASEDIR/android-amd64-4.9"
;;
x86|i386|i686)
	export ARCH=x86
	export HOST=i686-linux-android
	TOOLCHAIN="$BASEDIR/android-i386-4.9"
;;
arm64|aarch64)
	export ARCH=arm64
	export HOST=aarch64-linux-android
	TOOLCHAIN="$BASEDIR/android-arm64-4.9"
;;
*)
	export ARCH=arm
	export HOST=arm-linux-androideabi
	TOOLCHAIN="$BASEDIR/android-armhf-4.9"
;;
esac

case "$O" in
0) OPTIMIZE=;;
s) OPTIMIZE=-Os;;
3) OPTIMIZE=-O3;;
*) OPTIMIZE=-O2;;
esac

if [ "$STATIC" ]; then
	LINKER="-static"
else
	LINKER="-Wl,-dynamic-linker,"
	FPIE="-fPIE"
	LDPIE="$FPIE -pie"
	if [ "$TWRP" ]; then
		LINKER="$LINKER/sbin/linker"
	else
		LINKER="$LINKER/system/bin/linker"
	fi
fi

export ANDROID_NDK="$HOME/build/ndk/android-ndk-r10e"
export ANDROID_PREFIX="$ANDROID_NDK/prebuilt/android-$ARCH"

export PATH="$PATH:$TOOLCHAIN/bin"
export CROSS_COMPILE="$TOOLCHAIN/bin/$HOST-"
export TARGET="$HOST"
export HOST_CC="gcc"
export HOST_CXX="g++"
export HOST_CPP="cpp"
export HOST_AR="ar"
export HOST_AS="as"
export HOST_NM="nm"
export HOST_LD="ld"
export HOST_RANLIB="ranlib"
export HOST_STRIP="strip"
export CC="$CROSS_COMPILE$HOST_CC"
export CXX="$CROSS_COMPILE$HOST_CXX"
export CPP="$CROSS_COMPILE$HOST_CPP"
export AR="$CROSS_COMPILE$HOST_AR"
export AS="$CROSS_COMPILE$HOST_AS"
export NM="$CROSS_COMPILE$HOST_NM"
export LD="$CROSS_COMPILE$HOST_LD"
export RANLIB="$CROSS_COMPILE$HOST_RANLIB"
export STRIP="$CROSS_COMPILE$HOST_STRIP"
export CROSS="$CROSS_COMPILE"
export SYSROOT="$TOOLCHAIN/sysroot"
export DESTDIR="$SYSROOT"
export PREFIX="$DESTDIR/usr"
export CFLAGS="$OPTIMIZE $FPIE -fomit-frame-pointer --sysroot=\"${SYSROOT}\""
export CXXFLAGS="$CFLAGS"
export LDFLAGS="$LDPIE -mandroid -mbionic $LINKER"
export TARGET_SYS="Linux"
export TARGET_CFLAGS="$CFLAGS"
export TARGET_CXXFLAGS="$CXXFLAGS"
export TARGET_LDFLAGS="$LDFLAGS"
export TARGET_FLAGS="$TARGET_CFLAGS"

echo "Cross-compiling set up for $HOST"
echo "CC: $CC"
echo "CXX: $CXX"
echo "CFLAGS: $CFLAGS"
echo "CXXFLAGS: $CXXFLAGS"
echo "LDFLAGS: $LDFLAGS"
