#!/bin/bash

BASEDIR="$(readlink -f ~/build/toolchain)"

case "$ARCH" in
amd64|x86_64|x64)
	export ARCH=x86_64
	export HOST=x86_64-linux-android
        export ARCH_SYSROOT=arch-x86_64
	TOOLCHAIN="$BASEDIR/android-amd64-4.9"
;;
arm64|aarch64)
	export ARCH=arm64
	export HOST=aarch64-linux-android
        export ARCH_SYSROOT=arch-arm64
	TOOLCHAIN="$BASEDIR/android-arm64-4.9"
;;
*)
	export ARCH=arm
	export HOST=arm-linux-androideabi
	export ARCH_SYSROOT=arch-arm
	TOOLCHAIN="$BASEDIR/android-arm-4.9"
;;
esac

case "$O" in
0) OPTIMIZE=;;
s) OPTIMIZE=-Os;;
3) OPTIMIZE=-O3;;
*) OPTIMIZE=-O2;;
esac

if [ "$TWRP" ]; then
	LINKER="/sbin/linker"
else
	LINKER="/system/bin/linker"
fi

export ANDROID_NDK="~/build/ndk/android-ndk-r10e"
export ANDROID_PREFIX="$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64"
export SYSROOT="$TOOLCHAIN/sysroot"
export PATH="$PATH:$TOOLCHAIN/bin"
export CROSS_COMPILE="$TOOLCHAIN/bin/$HOST-"
export TARGET="$HOST"
export CFLAGS="$OPTIMIZE -fomit-frame-pointer -fPIE --sysroot=${SYSROOT}"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-fPIE -pie -mandroid -mbionic -Wl,-dynamic-linker,$LINKER"

# COMPILER-ADDRESS
export HOST_CC="gcc"
export HOST_CXX="g++"
export HOST_CPP="cpp"
export HOST_AR="ar"
export HOST_AS="as"
export HOST_NM="nm"
export HOST_LD="ld"
export HOST_RANLIB="ranlib"
export CC="$CROSS_COMPILE$HOST_CC"
export CXX="$CROSS_COMPILE$HOST_CXX"
export CPP="$CROSS_COMPILE$HOST_CPP"
export AR="$CROSS_COMPILE$HOST_AR"
export AS="$CROSS_COMPILE$HOST_AS"
export NM="$CROSS_COMPILE$HOST_NM"
export LD="$CROSS_COMPILE$HOST_LD"
export RANLIB="$CROSS_COMPILE$HOST_RANLIB"

export CROSS="$CROSS_COMPILE"
export DESTDIR="$SYSROOT"
export PREFIX="$DESTDIR/usr"
export TARGET_FLAGS="--sysroot $SYSROOT $TARGET_CFLAGS"
export TARGET_SYS="Linux"
export TARGET_CFLAGS="$CFLAGS"
export TARGET_CXXFLAGS="$CXXFLAGS"
export TARGET_LDFLAGS="$LDFLAGS"

echo "Cross-compiling set up for $HOST"
echo "CC: $CC"
echo "CXX: $CXX"
echo "CFLAGS: $CFLAGS"
echo "CXXFLAGS: $CXXFLAGS"
echo "LDFLAGS: $LDFLAGS"
