#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','/','r','o','o','t','/','b','u',
        'i','l','d','/','t','o','o','l','c','h','a','i','n','/','a','n','d','r',
        'o','i','d','-','a','r','m','-','4','.','9','/','b','i','n','/','a','r',
        'm','-','l','i','n','u','x','-','a','n','d','r','o','i','d','e','a','b',
        'i','-','g','c','c',' ','-','I','.',' ','-','I','.','.',' ','-','I','.',
        '.','/','i','n','c','l','u','d','e',' ',' ','-','O','\0'
    };
    #define PLATFORM "platform: dist"
    #define DATE "built on: Mon Jan 25 00:24:35 2016"
#endif
